# Generated by Django 3.2 on 2021-05-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目成员')),
                ('belong_to_section', models.CharField(choices=[('detection', '检测部'), ('integration', '综合部'), ('financial', '财务部'), ('security', '设备安全部'), ('management', '经营部')], default='', max_length=64, verbose_name='所属部门')),
                ('belong_to_group', models.CharField(choices=[('bridge-1', '桥梁1组'), ('bridge-2', '桥梁2组'), ('bridge-petrol', '桥梁巡检组'), ('road', '道路组'), ('tunnel', '隧道组'), ('material', '材料科研组')], default='', max_length=64, verbose_name='所属小组')),
                ('c_day', models.DateField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
            },
        ),
        migrations.CreateModel(
            name='AllProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('bridge', '桥梁项目'), ('road', '道路项目'), ('experiment', '室内试验'), ('others', '其他项目')], default='bridge', max_length=64, verbose_name='项目类型')),
                ('project_name', models.CharField(default='', max_length=64, unique=True, verbose_name='项目名称')),
                ('charge_person', models.CharField(default='', max_length=64, verbose_name='项目负责人')),
                ('project_status', models.SmallIntegerField(choices=[(0, '开始阶段'), (1, '中期阶段'), (2, '末期阶段'), (3, '项目结束'), (4, '项目暂停')], default=0, verbose_name='项目状态')),
                ('project_status_percent', models.CharField(default='', max_length=8, verbose_name='项目进度%')),
                ('former_status_percent', models.CharField(default='', max_length=8, verbose_name='昨日进度%')),
                ('start_day', models.DateField(blank=True, null=True, verbose_name='项目起始日期')),
                ('expect_finished_day', models.DateField(blank=True, null=True, verbose_name='预计完成日期')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('group_members', models.ManyToManyField(blank=True, to='projects.Member', verbose_name='小组成员')),
            ],
            options={
                'verbose_name': '项目总览',
                'verbose_name_plural': '项目总览',
            },
        ),
    ]
