# Generated by Django 3.1.3 on 2021-03-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '入库'), (1, '出库'), (2, '未知'), (3, '故障'), (4, '备用')], default=0, verbose_name='设备状态'),
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目进度')),
                ('memo', models.CharField(blank=True, max_length=64, unique=True, verbose_name='备注')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_level', to='assets.projectprogress')),
            ],
            options={
                'verbose_name': '项目进度',
                'verbose_name_plural': '项目进度',
            },
        ),
    ]
