# Generated by Django 3.1.3 on 2021-03-08 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20210308_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='所有项目')),
                ('memo', models.CharField(blank=True, max_length=64, unique=True, verbose_name='备注')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_level', to='assets.allprogress')),
            ],
            options={
                'verbose_name': '所有项目',
                'verbose_name_plural': '所有项目',
            },
        ),
        migrations.DeleteModel(
            name='ProjectProgress',
        ),
    ]
