# Generated by Django 3.1.3 on 2021-03-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20210308_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllProgress',
            new_name='AllProjects',
        ),
    ]
