# Generated by Django 3.1.3 on 2021-03-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20210320_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allprojects',
            options={'verbose_name': '项目总览', 'verbose_name_plural': '项目总览'},
        ),
        migrations.RemoveField(
            model_name='allprojects',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='allprojects',
            name='name',
        ),
        migrations.RemoveField(
            model_name='allprojects',
            name='parent_unit',
        ),
        migrations.AddField(
            model_name='allprojects',
            name='charge_person',
            field=models.CharField(default='', max_length=64, verbose_name='项目负责人'),
        ),
        migrations.AddField(
            model_name='allprojects',
            name='expect_finished_day',
            field=models.DateField(blank=True, null=True, verbose_name='预计完成日期'),
        ),
        migrations.AddField(
            model_name='allprojects',
            name='project_name',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='allprojects',
            name='project_type',
            field=models.CharField(choices=[('bridge', '桥梁项目'), ('road', '道路项目'), ('experiment', '室内试验'), ('others', '其他项目')], default='bridge', max_length=64, verbose_name='项目类型'),
        ),
        migrations.AddField(
            model_name='allprojects',
            name='start_day',
            field=models.DateField(blank=True, null=True, verbose_name='项目起始日期'),
        ),
        migrations.AddField(
            model_name='allprojects',
            name='status',
            field=models.CharField(choices=[('begin', '开始阶段'), ('medium', '中期阶段'), ('final', '末期阶段'), ('finished', '已完成'), ('unfinished', '未完成')], default='begin', max_length=64, verbose_name='项目状态'),
        ),
    ]
