# Generated by Django 3.1.3 on 2021-03-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20210320_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=64, verbose_name='项目名称')),
                ('commissioned_units', models.CharField(default='', max_length=64, verbose_name='委托单位')),
                ('report_name', models.CharField(default='', max_length=64, verbose_name='报告名称')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='报告日期')),
                ('report_number', models.CharField(default='', max_length=64, unique=True, verbose_name='报告编号')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '报告总览',
                'verbose_name_plural': '报告总览',
            },
        ),
    ]
