# Generated by Django 3.1.3 on 2021-03-22 17:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_reportlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlists',
            name='report',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('report', '报告'), ('plan', '方案'), ('record', '纪录'), ('order', '委托单'), ('photo', '照片')], default='', max_length=30, verbose_name='存档资料'),
        ),
        migrations.AddField(
            model_name='reportlists',
            name='seal',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('detectSeal', '检测专用章'), ('CMASeal', 'CMA专用章'), ('officialSeal', '公章')], default='', max_length=31, verbose_name='盖章类型'),
        ),
    ]
