# Generated by Django 3.1.3 on 2021-03-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_reportlists_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': '实验室', 'verbose_name_plural': '实验室'},
        ),
        migrations.AddField(
            model_name='idc',
            name='apparatus_status',
            field=models.CharField(choices=[(0, '入库'), (1, '出库'), (2, '待检'), (4, '送检'), (5, '已标定'), (6, '未知'), (7, '故障')], default=0, max_length=64, verbose_name='设备状态'),
        ),
        migrations.AddField(
            model_name='idc',
            name='item',
            field=models.CharField(default='', max_length=128, verbose_name='设备名称'),
        ),
        migrations.AddField(
            model_name='idc',
            name='laboratory_status',
            field=models.BooleanField(default=False, verbose_name='是否开放'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='实验室名称'),
        ),
    ]
