# Generated by Django 3.1.3 on 2021-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20210325_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='app/media', verbose_name='文件')),
                ('file_name', models.CharField(default='logfile_name', max_length=128, verbose_name='文件名称')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('host_ip', models.CharField(default='10.168.1.113', max_length=128, verbose_name='主机IP')),
                ('memo', models.CharField(default='', max_length=128, verbose_name='备注说明')),
            ],
        ),
    ]
