# Generated by Django 3.1.3 on 2021-03-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_logfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogFiles',
            new_name='LogFile',
        ),
    ]
