# Generated by Django 3.1.3 on 2021-04-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num_data', models.IntegerField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='assets.article')),
            ],
        ),
    ]
