# Generated by Django 3.1.3 on 2021-04-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='article',
        ),
        migrations.AddField(
            model_name='allprojects',
            name='project_status_percent',
            field=models.CharField(default='', max_length=16, verbose_name='项目进度百分比'),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='file',
            field=models.FileField(upload_to='media/file/', verbose_name='文件'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
