# Generated by Django 3.1.3 on 2021-04-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_auto_20210406_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprojects',
            name='percent',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='项目完成进度百分比%'),
        ),
        migrations.AlterField(
            model_name='allprojects',
            name='project_status_percent',
            field=models.CharField(default='', max_length=8, verbose_name='项目进度百分比'),
        ),
    ]
