# Generated by Django 3.1.3 on 2021-04-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_auto_20210406_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allprojects',
            name='percent',
        ),
        migrations.AlterField(
            model_name='allprojects',
            name='project_status_percent',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='项目完成进度百分比%'),
        ),
    ]
