# Generated by Django 3.1.3 on 2021-04-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_auto_20210406_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprojects',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
