# Generated by Django 3.1.3 on 2021-04-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_allprojects_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprojects',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='allprojects',
            name='project_status',
            field=models.SmallIntegerField(choices=[(0, '开始阶段'), (1, '中期阶段'), (2, '末期阶段'), (3, '项目结束'), (4, '项目暂停')], default=0, verbose_name='项目状态'),
        ),
    ]
