# Generated by Django 3.1.3 on 2021-04-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_auto_20210407_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprojects',
            name='former_status_percent',
            field=models.CharField(default='', max_length=8, verbose_name='项目前一天进度%'),
        ),
    ]
