# Generated by Django 3.1.3 on 2021-04-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_allprojects_former_status_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目成员')),
                ('c_day', models.DateField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
            },
        ),
        migrations.AddField(
            model_name='allprojects',
            name='group_members',
            field=models.ManyToManyField(blank=True, to='assets.Member', verbose_name='小组成员'),
        ),
    ]
