# Generated by Django 3.1.3 on 2021-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_auto_20210408_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='belong_to',
            new_name='belong_to_section',
        ),
        migrations.AddField(
            model_name='member',
            name='belong_to_group',
            field=models.CharField(default='', max_length=8, verbose_name='所属小组'),
        ),
    ]
