# Generated by Django 3.1.3 on 2021-04-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_auto_20210408_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='belong_to_group',
            field=models.CharField(choices=[('bridge-1', '桥梁1组'), ('bridge-2', '桥梁2组'), ('bridge-petrol', '桥梁巡检组'), ('road', '道路组'), ('tunnel', '隧道组'), ('material', '材料科研组')], default='', max_length=64, verbose_name='所属小组'),
        ),
        migrations.AlterField(
            model_name='member',
            name='belong_to_section',
            field=models.CharField(choices=[('detection', '检测部'), ('integration', '综合部'), ('financial', '财务部'), ('security', '设备安全部'), ('management', '经营部')], default='', max_length=64, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='项目成员'),
        ),
    ]
