# Generated by Django 3.1.3 on 2021-04-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_auto_20210408_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='图片上传'),
        ),
    ]
