# Generated by Django 3.1.3 on 2021-04-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_logfile_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/file/', verbose_name='文件'),
        ),
    ]
