# Generated by Django 3.2 on 2021-04-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_auto_20210408_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_type', models.CharField(choices=[('CHL', '掺合料'), ('DL', '道路'), ('DJJZ', '地基、基桩'), ('FMH', '粉煤灰'), ('GJ', '钢筋'), ('HX', '化学'), ('HNT', '混凝土'), ('JL', '集料'), ('JC', '监测'), ('JA', '交安'), ('JS', '金属'), ('KZF', '矿渣粉'), ('LQ', '沥青'), ('QT', '其他'), ('QH', '桥涵'), ('SN', '水泥'), ('SD', '隧道'), ('TG', '土工')], default='', max_length=64, verbose_name='类别')),
                ('box_type', models.CharField(choices=[('1', '①'), ('2', '②'), ('3', '③'), ('4', '④'), ('5', '⑤'), ('6', '⑥'), ('7', '⑦'), ('8', '⑧'), ('9', '⑨'), ('10', '⑩')], default='', max_length=4, verbose_name='所在盒子')),
                ('number', models.CharField(default='', max_length=4, verbose_name='序号')),
                ('name', models.CharField(max_length=100, verbose_name='规范标准名称')),
                ('standard_ID', models.CharField(default='', max_length=64, unique=True, verbose_name='标准编号')),
                ('in_standard_ID', models.CharField(default='', max_length=64, unique=True, verbose_name='公司内部编号')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('update_situation', models.CharField(default='', max_length=64, verbose_name='更新情况')),
                ('file', models.FileField(null=True, upload_to='static/file', verbose_name='上传规范')),
            ],
            options={
                'verbose_name': '规范浏览',
                'verbose_name_plural': '规范浏览',
            },
        ),
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
