# Generated by Django 3.2 on 2021-05-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_auto_20210427_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllProjects',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
