# Generated by Django 3.0.6 on 2022-02-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_auto_20210509_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='update_situation',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('word文档_07', 'docx'), ('excel文档_07', 'xlsx'), ('图片_1', 'JPEG'), ('图片_2', 'PNG')], default='', max_length=64, verbose_name='文件类型'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='update_type',
            field=models.CharField(choices=[('status_1', '已更新'), ('status_2', '未更新'), ('status_3', '已作废')], default='', max_length=8, verbose_name='更新情况'),
        ),
        migrations.AddField(
            model_name='reportlists',
            name='file',
            field=models.FileField(null=True, upload_to='static/file', verbose_name='上传文件'),
        ),
        migrations.AlterField(
            model_name='reportlists',
            name='report_number',
            field=models.CharField(blank=True, default='', max_length=500, null=True, unique=True, verbose_name='报告编号'),
        ),
    ]
