# Generated by Django 3.2 on 2021-05-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(default='', max_length=64, verbose_name='新增功能')),
            ],
            options={
                'verbose_name': '新增功能',
                'verbose_name_plural': '新增功能',
            },
        ),
    ]
