# Generated by Django 3.2 on 2021-05-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='name',
            field=models.CharField(default='', max_length=8, unique=True, verbose_name='职员姓名'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='section',
            field=models.CharField(choices=[('IntegratedDepartment', '综合部'), ('DetectionDepartment', '检测部'), ('ContractDepartment', '合约部'), ('SecurityDepartment', '安全部'), ('FinanceDepartment', '财务部')], default='', max_length=64, verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='tel',
            field=models.CharField(default='', max_length=16, unique=True, verbose_name='联系方式'),
        ),
    ]
