# Generated by Django 3.0.6 on 2021-05-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210517_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
